---
# tasks file for role_labo_prometheus

- name: create setting directory for prometheus
  file:
    path: /etc/prometheus/settings
    state: directory
    mode: '0755'

- name: download config file prometheus
  get_url:
    url: https://raw.githubusercontent.com/oxydedefer/labo_config_files/master/prometheus.yml
    dest: /etc/prometheus/settings/prometheus.yml
    force: yes
- name: run prometheus container
  docker_container:
    name: prometheus-ansible
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus/settings/prometheus.yml:/etc/prometheus/prometheus.yml
